# Generated by Django 3.0.8 on 2020-07-30 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='URL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_url', models.URLField(max_length=2000)),
                ('shortened_url', models.URLField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'URLs',
            },
        ),
    ]
