# Generated by Django 3.0.8 on 2020-07-30 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200730_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='shortened_suffix',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
