# Generated by Django 3.0.8 on 2020-07-30 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200730_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='shortened_suffix',
            field=models.CharField(max_length=7, unique=True),
        ),
    ]
